<?php
$title = 'Add new vacancy';
$this->headTitle($title);
print $this->showMessages();
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('vacancy', array('controller' => 'vacancy' , 'action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('vacancyId'));
?>
<div class="form-group departments">
    <?= $this->formRow($form->get('departmentsDepartment'))?>
</div>
<div class="checkbox"><?= $this->formRow($form->get('enabled'))?></div>
<?php foreach($languages as $row):?>
<div class="panel panel-default">
    <div class="panel-heading"><?= $row->title?></div>
    <div class="panel-body" id="block<?= $row->languageId?>">
        <div class="form-group"><?= $this->formRow($form->get("title_{$row->languageId}"))?></div>
        <div class="form-group"><?= $this->formRow($form->get("text_{$row->languageId}"))?></div>
    </div>
</div>
<?php endforeach?>
<div class="form-group"><?= $this->formSubmit($form->get('submit'))?></div>
<?php
echo $this->form()->closeTag();
?>
<script type="text/javascript">
    $(function(){
       $(".panel-body:not([id='block<?= $this->defLang?>'])").hide();
       $('.panel-heading').click(function(){
          $(this).next('.panel-body').slideToggle(); 
       });
    });
</script>