<?php
$title = 'Edit departmet';
$this->headTitle($title);
print $this->showMessages();
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('department', array('action' => 'edit', 'id' => $this->id)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('departmentId'));
?>
<div class="form-group">
    <?= $this->formRow($form->get('title'))?>
</div>
   <?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();