<div class="row">
    <div class="col-md-4">
        <form id="formFilter">
        <h4>Languages</h4>
        <?php foreach($this->languages as $language):?>
        <div class="checkbox">
            <label>
                <input type="radio" name="lang" <?= $this->filter['lang'] == $language['languageId'] ? 'checked="checked"' : ''?> value="<?= $language['languageId']?>">
                <?= $language['title']?>
            </label>
        </div>
        <?php endforeach?>
        <h4 style="margin-top: 20px">Departments</h4>
        <?php foreach($this->departments as $department):?>
        <div class="checkbox">
            <label>
                <input type="checkbox" name="dep[]" <?= in_array($department['departmentId'], $this->filter['dep']) ? 'checked="checked"' : ''?> value="<?= $department['departmentId']?>">
                <?= $department['title']?>
            </label>
        </div>
        <?php endforeach?>
        <div class="pt-20">
            <button class="btn btn-default" type="submit">Filter</button>
        </div>
        </form>
    </div>
    <div class="col-md-8">
        <?php foreach($this->vacancies as $row):?>
        <div class="container-fluid">
            <div class="row">
                <h4><?= $row['vacancyTitle']?></h4>
                <p><?= $row['vacancyText']?></p>
            </div>
        </div>
        <?php endforeach?>
    </div>
</div>
